version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kirguir/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DATABASE_PASSWORD: ${DB_PASSWORD}
      GII_PASSWORD: ${GII_PASSWORD}
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./_dev/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./log:/var/log/nginx
      - ./_dev/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: logs
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./_dev/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Volumes
volumes:
  dbdata:
    driver: local

#Docker Networks
networks:
  app-network:
    driver: bridge
